#これらはサポートされている資金調達モデルプラットフォームです

github: #最大4つのGitHubスポンサー対応のユーザー名に置き換えます（例：[user1、user2]）
patreon: #単一のPatreonユーザー名に置き換えます
open_collective: #単一のOpen Collectiveユーザー名に置き換えます
ko_fi: #単一のKo-fiユーザー名に置き換えます
tidelift: #単一のTideliftプラットフォーム名/パッケージ名で置き換えます。例：npm / babel
community_bridge: #単一のCommunity Bridgeプロジェクト名に置き換えます（例：cloud-foundry）
liberapay: #1つのLiberapayユーザー名に置き換えます
issuehunt: #単一のIssueHuntユーザー名に置き換えます
otechie: #単一のOtechieユーザー名に置き換えます
custom: #最大4つのカスタムスポンサーシップURLで置き換えます（例：['link1'、 'link2']）